### ISSUE TITLE
Selecting seasons 

### ISSUE THREAD

**Issue by JunkHam04** [Infinite-Null/NekoFlix#3]
Hello, so before the question I just wanted to thank you for this great app because it's just so clean and works perfectly for a manga and anime app ( I mean together in one app is just brilliant) ; but I just found the first season in each anime , where do we select the other seasons please?

**Comment by Infinite-Null** [comment]
Thank you bro for appreciation.
For season you have to search it
Example: Attack on titan season 2

**Comment by Infinite-Null** [comment]
> My bad I didn't notice, thank you for your reply 👍

Always 😄
