### ISSUE TITLE
Streaming api

### ISSUE THREAD

**Issue by maropboia** [Infinite-Null/NekoFlix#4]
I have own anime collection and made a site. Why not integrate in ur app?  https://animebd.pages.dev/

**Comment by Infinite-Null** [comment]
I have gone through your website and it has really awesome UI which I can use for nekoflixTV os but as I done some research on your website there were some issues like for episode images request fails with 404 not found.

![Screenshot_20240430_132500](https://github.com/Infinite-Null/NekoFlix/assets/97950192/88465341-c1ca-419e-85b9-f83dbf2ff13e)
   
Even I found one repo in your github https://github.com/maropboia/AnimeDexLite 
which is forked from https://github.com/TechShreyash/AnimeDexLite 
it seems that with your commit you have changed the api url.

**Comment by maropboia** [comment]
Yes because it uses 3d party hosted videos and scrap thumbnail from site, maybe they blocked crawler

**Comment by Infinite-Null** [comment]
Your project is really great and have a great ui can you please provide me with your api?

**Comment by maropboia** [comment]
> Your project is really great and have a great ui can you please provide me with your api?

Sorry to bother you brother,,i can provide you api but, it would be foolish for you to use it because dmca is taking down this, this is why main project is archived (you can see). 
And it has a lot of bugs, and after somedays it stops working as main api changes.

**Comment by maropboia** [comment]
Your project is great and i love this ui. Don't use my api because dmca is strict. (Note: I'm also deleting forked repo for this)

**Comment by maropboia** [comment]
![Uploading Screenshot_20240501-124506.jpg…]()
 
And it's now offline https://animebd.pages.dev/anime?anime_id=Tensei%20Shitara%20Dai%20Nana%20Ouji%20Dattanode%2C%20Kimamani%20Majutsu%20wo%20Kiwamemasu

**Comment by maropboia** [comment]
![Screenshot_20240501-124506](https://github.com/Infinite-Null/NekoFlix/assets/164220066/cbd5ed77-0e66-4715-bd79-8d9c7875280e)
